Safe cached client
konveyor/mig-controller pull request #1037
Opened 2021-03-28 02:40 UTC by djwhatle

Blocks until the cache catches up so that we can use the cache without worrying about race conditions

2021-03-29 14:10 UTC, djwhatle commented on pkg/compat/client.go
> +			golog.Print(fmt.Sprintf("\n\n\n\n\n\n<<<[CREATE OBJ]>>> kind=[%v] key=[%v/%v]\n\n\n\n\n\n", kind, uNs, uName))
Ignore this logger and log statements, will be removed but helped to understand while debugging.

2021-03-31 17:06 UTC, pranavgaikwad commented
I used this PR and I would just like to post the results here.

1. Before this PR, `RunRsyncOperations` phase in DVM took about 10-15 seconds to run once: 

![Screenshot from 2021-03-31 13-05-20](https://user-images.githubusercontent.com/9839757/113183227-c7e23980-9221-11eb-8cc2-c69a54ea162a.png)

2. After this PR, the same phase takes a few seconds (worst case) to run once:

![Screenshot from 2021-03-31 13-06-04](https://user-images.githubusercontent.com/9839757/113183320-e0525400-9221-11eb-9baf-d2f326b17bab.png)

2021-05-20 13:54 UTC, djwhatle commented on pkg/controller/directvolumemigration/stunnel.go
> +
Whoah, didn't mean to pick this up. Will need to grab this file off master.

2021-05-20 18:39 UTC, pranavgaikwad requested changes
Overall looks good to me. I will wait for operator PR for the feature flag.

2021-05-26 20:20 UTC, djwhatle commented
Need to rebase. Doing it now.

2021-05-26 20:28 UTC, djwhatle commented
Squashed to make the rebase easier.

2021-06-03 15:19 UTC, djwhatle commented
Just got the rebase finished. Need to do a bit of testing to verify that everything is working as expected.

2021-06-03 17:34 UTC, pranavgaikwad approved these changes
LGTM

2021-06-03 19:07 UTC, sseago approved these changes
The manager stop changes look sane to me.

2021-06-03 19:24 UTC, merged