State Transfer API Changes
konveyor/mig-controller pull request #1159
Opened 2021-07-27 14:33 UTC by pranavgaikwad

This PR introduces two API changes: 

1. MigPlan - Introduces new fields to provide list of included resources in the Backup and an optional Label Selector

2. DirectVolumeMigration - Introduces new fields for TargetName on each PVC

2021-07-27 15:48 UTC, shawn-hurley approved these changes
I believe that all of these fields must be marked optional, and I believe that more documentation on usage will be helpful

2021-07-27 15:48 UTC, shawn-hurley commented on pkg/apis/migration/v1alpha1/directvolumemigration_types.go
> +	TargetName            string                            `json:"targetName,omitempty"`
I would like to see a comment or something here that explains usage, as it appears we have some helper.

It also appears that this is not optional, I believe that we must mark it as such.

2021-07-27 15:48 UTC, shawn-hurley commented on pkg/apis/migration/v1alpha1/migplan_types.go
> +	IncludedResources []*metav1.GroupKind `json:"includedResources,omitempty"`
These must be optional as well, can we document what the default values are for this?

2021-07-27 15:48 UTC, shawn-hurley commented on pkg/apis/migration/v1alpha1/migplan_types.go
> +	LabelSelector *metav1.LabelSelector `json:"labelSelector,omitempty"`
These must be optional as well, I would also document what happens when this is not added.

2021-07-27 15:49 UTC, shawn-hurley requested changes
wrong selection sorry

2021-08-04 19:15 UTC, alaypatel07 approved these changes
VISIACK

2021-08-06 17:42 UTC, shawn-hurley approved these changes
LGTM

2021-08-06 18:04 UTC, merged