Bug 2031793: Add validation for provided resource list in the migplan
konveyor/mig-controller pull request #1242
Opened 2021-12-14 16:54 UTC by pranavgaikwad

2021-12-15 14:44 UTC, sseago requested changes
A couple of minor changes (typo, copy-and-paste) but otherwise looks good.

2021-12-15 14:44 UTC, sseago commented on pkg/controller/migplan/validation.go
> +	err = r.validateInludedResources(ctx, plan)
Typo: s/Inluded/Included/

2021-12-15 14:44 UTC, sseago commented on pkg/controller/migplan/validation.go
> +func (r ReconcileMigPlan) validateInludedResources(ctx context.Context, plan *migapi.MigPlan) error {
Typo: s/Inluded/Included/

2021-12-15 14:44 UTC, sseago commented on pkg/controller/migplan/validation.go
> +	// Hooks
// Included resources

2021-12-15 14:48 UTC, pranavgaikwad commented on pkg/controller/migplan/validation.go
> +	err = r.validateInludedResources(ctx, plan)
I gotta take an eye exam :P

2021-12-16 18:09 UTC, sseago approved these changes

2021-12-16 18:40 UTC, merged