MIG-351: let the migration run to completion on partial velero restore failure
konveyor/mig-controller pull request #760
Opened 2020-11-10 16:20 UTC by alaypatel07

2020-11-11 01:16 UTC, alaypatel07 commented
![image](https://user-images.githubusercontent.com/8192650/98753034-72e87880-2391-11eb-8660-f6712cdb0c73.png)

This seems to work as expected.

The status condition in migmigration yaml is as follows:
```
  status:
    conditions:
    - category: Warn
      durable: true
      lastTransitionTime: "2020-11-11T01:12:57Z"
      message: 'Restore: openshift-migration/ocp-28021-istags-mig-1605056181-zmmf7
        partially failed.'
      status: "True"
      type: VeleroRestorePartiallyFailed
    - category: Warn
      durable: true
      lastTransitionTime: "2020-11-11T01:12:57Z"
      message: 'Backup: openshift-migration/ocp-28021-istags-mig-1605056181-zmmf7
        partially failed.'
      status: "True"
      type: VeleroBackupPartiallyFailed
    - category: Advisory
      durable: true
      lastTransitionTime: "2020-11-11T01:13:25Z"
      message: The migration has completed successfully.
      reason: Completed
      status: "True"
      type: Succeeded
    itinerary: Final
    observedDigest: 934d262d32bea794a5ca1345d12a11708a4c801d87f73f3d28bd9a1634c4c934
    phase: Completed
    pipeline:
    - completed: "2020-11-11T00:59:32Z"
      message: Completed
      name: Prepare
      started: "2020-11-11T00:56:56Z"
    - completed: "2020-11-11T01:00:19Z"
      message: Completed
      name: Backup
      progress:
      - 'Backup openshift-migration/ocp-28021-istags-mig-1605056181-9hqt7: Completed'
      started: "2020-11-11T00:59:32Z"
    - completed: "2020-11-11T01:11:20Z"
      message: Completed
      name: StageBackup
      progress:
      - 'Backup openshift-migration/ocp-28021-istags-mig-1605056181-l7jxb: Not replicated'
      started: "2020-11-11T01:00:19Z"
    - completed: "2020-11-11T01:11:47Z"
      message: Completed
      name: StageRestore
      progress:
      - 'Restore openshift-migration/ocp-28021-istags-mig-1605056181-5bvlr: Completed'
      started: "2020-11-11T01:11:20Z"
    - completed: "2020-11-11T01:13:11Z"
      message: Completed
      name: Restore
      progress:
      - 'Restore: openshift-migration/ocp-28021-istags-mig-1605056181-zmmf7 partially
        failed.'
      started: "2020-11-11T01:11:47Z"
    - completed: "2020-11-11T01:13:25Z"
      message: Completed
      name: Final
      started: "2020-11-11T01:13:11Z"
    startTimestamp: "2020-11-11T00:56:56Z"
```

2020-11-11 20:57 UTC, alaypatel07 commented
```
status:
  conditions:
  - category: Warn
    durable: true
    lastTransitionTime: "2020-11-11T20:27:32Z"
    message: 'Final Restore: openshift-migration/ocp-28021-istags-mig-1605125961-2rstk
      partially failed on dest cluster'
    status: "True"
    type: VeleroFinalRestorePartiallyFailed
  - category: Advisory
    durable: true
    lastTransitionTime: "2020-11-11T20:28:00Z"
    message: The migration has completed with warning, please look at `Warn` conditions.
    reason: Completed
    status: "True"
    type: SucceededWithWarnings
```

2020-11-11 22:15 UTC, sseago requested changes
A couple minor changes, otherwise looks good.

2020-11-11 22:15 UTC, sseago commented on pkg/controller/migmigration/backup.go
> -		reasons = append(reasons, message)
This change should go into BackupPhasePartiallyFailed rather than BackupPhaseFailed

2020-11-11 22:15 UTC, sseago commented on pkg/controller/migmigration/restore.go
> +func (t *Task) setInitialBackupPartialFailureWarning(backup *velero.Backup) {
This func should go into backup.go

2020-11-11 22:15 UTC, sseago commented on pkg/controller/migmigration/restore.go
> +func (t *Task) setStageBackupPartialFailureWarning(backup *velero.Backup) {
This func should go into backup.go

2020-11-11 22:28 UTC, djwhatle approved these changes
LGTM

2020-11-11 22:28 UTC, djwhatle commented on pkg/controller/migmigration/migrate.go
> +		warnings := task.Owner.Status.FindConditionByCategory(migapi.Warn)
👍

2020-11-11 22:28 UTC, djwhatle commented on pkg/controller/migmigration/migrate.go
> +				Message:  "The migration has completed with warning, please look at `Warn` conditions.",
suggest `warning` -> `warnings`

2020-11-11 22:36 UTC, sseago approved these changes
LGTM

2020-11-12 15:07 UTC, djwhatle approved these changes

2020-11-12 15:08 UTC, merged