Bug 1912246 - Add checksum flag to rsync when verify is specified
konveyor/mig-controller pull request #890
Opened 2021-01-14 20:10 UTC by dymurray

2021-01-18 19:17 UTC, alaypatel07 commented on pkg/controller/directvolumemigration/rsync.go
> +				rsyncCommand = append(rsyncCommand, "--checksum")
I have a question here: if a pod already exists without the checksum command on the source side, https://github.com/konveyor/mig-controller/pull/890/files#diff-7299a3c4e600e2733571d1d39c64bbfe6c7e448a6bb15aa472514a173d3095c0R1015 we would not be creating one. So we are promissing user to run with checksum but dont actual run it be checksum in that case?

2021-01-18 19:17 UTC, alaypatel07 commented on pkg/controller/directvolumemigration/rsync.go
> +				rsyncCommand = append(rsyncCommand, "--checksum")
this will work for 90% of the case I think but might need a followup to fix it for good

2021-01-18 20:23 UTC, alaypatel07 commented on pkg/apis/migration/v1alpha1/directvolumemigration_types.go
> +	Verify                bool                              `json:"verify,omitEmpty"`
this will require a mig-operator PR?

2021-01-18 21:55 UTC, alaypatel07 requested changes
Needs a rebase and https://github.com/dymurray/mig-controller/pull/3

2021-01-19 22:14 UTC, dymurray commented
https://github.com/konveyor/mig-operator/pull/553

2021-01-19 22:25 UTC, alaypatel07 approved these changes
ACK

2021-01-19 22:29 UTC, merged