Bug 1920683: Turn off munge symlinks to perserve symlinks
konveyor/mig-controller pull request #925
Opened 2021-01-26 21:20 UTC by shawn-hurley

2021-01-26 21:50 UTC, djwhatle approved these changes

2021-01-27 04:23 UTC, alaypatel07 requested changes
this needs to be rebased after merging https://github.com/konveyor/mig-controller/pull/923

2021-01-27 04:23 UTC, alaypatel07 commented on pkg/controller/directvolumemigration/rsync.go
>          fake super = yes
just to make sure this line is removed

2021-01-27 15:01 UTC, eriknelson approved these changes

2021-01-27 16:18 UTC, merged